// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webbuilder.api.data;

#nullable disable

namespace webbuilder.api.Migrations
{
    [DbContext(typeof(ElementStoreContext))]
    partial class ElementStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webbuilder.api.models.Element", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<string>("Href")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "href");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isSelected");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "order");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "projectId");

                    b.Property<string>("Src")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "src");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "styles");

                    b.Property<string>("TailwindStyles")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tailwindStyles");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "y");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Elements");

                    b.HasDiscriminator<string>("Type").HasValue("Element");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("webbuilder.api.models.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("webbuilder.api.models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subdomain")
                        .HasColumnType("text")
                        .HasColumnName("subdomain");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("webbuilder.api.models.Setting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ElementId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "settingType");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "settings");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("webbuilder.api.models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webbuilder.api.models.ButtonElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.Property<string>("ButtonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "buttonType");

                    b.Property<string>("ElementId")
                        .HasColumnType("text");

                    b.HasIndex("ElementId");

                    b.HasDiscriminator().HasValue("Button");
                });

            modelBuilder.Entity("webbuilder.api.models.CarouselElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Carousel");
                });

            modelBuilder.Entity("webbuilder.api.models.FormElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Form");
                });

            modelBuilder.Entity("webbuilder.api.models.FrameElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Frame");

                    b.HasAnnotation("Relational:JsonPropertyName", "element");
                });

            modelBuilder.Entity("webbuilder.api.models.ImageElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("webbuilder.api.models.InputElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Input");
                });

            modelBuilder.Entity("webbuilder.api.models.LinkElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Link");
                });

            modelBuilder.Entity("webbuilder.api.models.ListElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("ListItem");
                });

            modelBuilder.Entity("webbuilder.api.models.SelectElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "options");

                    b.HasDiscriminator().HasValue("Select");
                });

            modelBuilder.Entity("webbuilder.api.models.TextElement", b =>
                {
                    b.HasBaseType("webbuilder.api.models.Element");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("webbuilder.api.models.Element", b =>
                {
                    b.HasOne("webbuilder.api.models.Element", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("webbuilder.api.models.Project", "Project")
                        .WithMany("Elements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("webbuilder.api.models.Image", b =>
                {
                    b.HasOne("webbuilder.api.models.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webbuilder.api.models.Project", b =>
                {
                    b.HasOne("webbuilder.api.models.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("webbuilder.api.models.Setting", b =>
                {
                    b.HasOne("webbuilder.api.models.Element", "Element")
                        .WithMany("Settings")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Element");
                });

            modelBuilder.Entity("webbuilder.api.models.ButtonElement", b =>
                {
                    b.HasOne("webbuilder.api.models.FrameElement", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("webbuilder.api.models.Element", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("webbuilder.api.models.Project", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("webbuilder.api.models.User", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
